spring:
  security:
    oauth2:
      registration:
        google:
          client-id: 1021343492232-5blret1okhs6dt1ort0s9nph7uuu590v.apps.googleusercontent.com
          client-secret: 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
          scope: email, name
          redirect-uri:
            - http://localhost:8080/oauth2/callback
            - http://localhost:8080/api/my-page

oauth:
  authorizedRedirectUri: localhost:8080/api/accommodations
#        naver:
#          client-name: Naver
#          redirect-uri: http://localhost:8080/login/oauth2/naver
#          authorization-grant-type: authorization_code
#          client-id:
#          client-secret:
#          scope: name, email, profile_image
#        kakao:
#          client-name: Kakao
#          redirect-uri: http://localhost:8080/login/oauth2/kakao
#          authorization-grant-type: authorization_code
#          client-id:
#          client-secret:
#          scope: account_email, profile_nickname, profile_image

#      provider:
#        naver:
#          authorization-uri: https://nid.naver.com/oauth2.0/authorize
#          token-uri: https://nid.naver.com/oauth2.0/token
#          user-info-uri: https://openapi.naver.com/v1/nid/me
#          user-name-attribute: response
#        kakao:
#          authorization-uri: https://kauth.kakao.com/oauth/authorize
#          token-uri: https://kauth.kakao.com/oauth/token
#          user-info-uri: https://kapi.kakao.com/v2/user/me
#          user-name-attribute: id
