spring:
  profiles:
    include: oauth
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  hibernate:
    ddl-auto: validate
  datasource:
    url: jdbc:mysql://project-mini.cfag6omiojwb.ap-northeast-2.rds.amazonaws.com:3306/accommodation?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: mini12345

token:
  secret:
    tokenKey: MiniProjectPracticeJWTSecretKey1234567890
  accessToken:
    plus-minute: 120
    plus-hour: 2
  refreshToken:
    plus-hour: 24